Add virt-who reporting
ares/foreman_maintain pull request #2
Opened 2024-06-21 19:32 UTC by chris1984

Output of PR:

```bash
With data:
virt_who_configurations: 2
Hypervisor types:
- hypervisor_type: esx
- hypervisor_type: esx

Without data:
virt_who_configurations: 0
Hypervisor types: []
compute_resource_vmware_count: 0
```

2024-06-24 07:14 UTC, ares requested changes
Thanks Chris, I think it would be good to see each virtualization mentioned explicitly, as it will be easier to process. In theory, we could sum all of such counters to get the overall count, but I think it's also fine to keep the global counter.

2024-06-24 07:14 UTC, ares commented on definitions/reports/virt_who.rb
> +          hypervisor_types = feature(:foreman_database).query("SELECT hypervisor_type FROM foreman_virt_who_configure_configs")
I think it would be better to hardcode the list of provider and have the data for each mentioned explicitly. E.g.

foreman_virt_who_configure_esx_count: 1
foreman_virt_who_configure_kubevirt_count: 0

The list of possible virtualizations based on [source code](https://github.com/candlepin/virt-who/tree/main/virtwho/virt): ahv, esx, fakevirt, hyperv, kubevirt, libvirtd

2024-06-24 07:14 UTC, ares commented on definitions/reports/virt_who.rb
> +          self.data = { "virt_who_configurations": count,
Ideally, use "_count" suffix for counters, so `virt_who_configurations_count` in this case

2024-12-06 11:13 UTC, adamruzicka commented
@chris1984 ping

2024-12-09 15:53 UTC, chris1984 commented
> @chris1984 ping

I can swing back to this in a few weeks after I get back from PTO.

2025-06-30 18:05 UTC, closed without merging